export const GroupActionTypes = {
  SEARCH_GROUP_START: 'SEARCH_GROUP_START',
  SEARCH_GROUP_SUCCESS: 'SEARCH_GROUP_SUCCESS',
  SEARCH_GROUP_ERROR: 'SEARCH_GROUP_ERROR',
  SET_CURRENT_GROUP: 'SET_CURRENT_GROUP',
  FETCH_CLASSES_START: 'FETCH_CLASSES_START',
  FETCH_CLASSES_SUCCESS: 'FETCH_CLASSES_SUCCESS',
  FETCH_CLASSES_ERROR: 'FETCH_CLASSES_ERROR',
}