export const UserActionTypes = {
  LOG_IN_START: 'LOG_IN_START',
  SIGN_UP_START: 'SIGN_UP_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  LOG_OUT: 'LOG_OUT',
  ADD_GROUP_START: 'ADD_GROUP_START',
  REMOVE_GROUP_START: 'REMOVE_GROUP_START',
  GROUPS_UPDATE_SUCCESS: 'GROUPS_UPDATE_SUCCESS',
  GROUPS_UPDATE_ERROR: 'GROUPS_UPDATE_ERROR',
}